### ISSUE TITLE
Bugreport 2FA ipadOS

### ISSUE THREAD

**Issue by wAuner** [simple-login/Simple-Login-iOS#1]
Hi,

something weird happened the first time I logged in the ipadOS app.
I‘ve setup 2FA and it asked me for the OTP code. But then it logged me in although I didn‘t enter anything.
I wasn‘t able to replicate it since then. 
But I‘ve noticed something else: When open an app in multitasking mode (swipe from right, not split screen, to access my password manager) it enters some numbers which I can see for a split second and then get the error message wrong code.

Is the app somehow trying to access the clipboard?

**Comment by ntnhon** [comment]
Hi @wAuner, yes it is intended behaviour. The app tries to fill out the code for you if it found out that there is a code (a 6 digits only string) in the clipboard.

This is the function that does the clipboard check:

` @objc private func applicationDidBecomeActive() {
        guard let copiedText = UIPasteboard.general.string,
            copiedText.count == 6,
            let _ = Int(copiedText) else { return }
        
        showErrorLabel(false)
        
        firstNumberLabel.text = String(copiedText[0])
        secondNumberLabel.text = String(copiedText[1])
        thirdNumberLabel.text = String(copiedText[2])
        fourthNumberLabel.text = String(copiedText[3])
        fifthNumberLabel.text = String(copiedText[4])
        sixthNumberLabel.text = String(copiedText[5])
        
        verify(code: copiedText)
    }`

Which can be found [here](https://github.com/simple-login/Simple-Login-iOS/blob/master/Simple%20Login/Simple%20Login/Controllers/Login/VerificationViewController.swift#L76-L91).

Let me know if you still have any question regarding verification step.

**Comment by wAuner** [comment]
hey @ntnhon, thanks for your quick replies.
I see why you would do that. However, it only worked 1 out of 5 times I tested it. I use 1pasword to log in and it then copies the OTP code in my clipboard.
My guess is that the clipboard access is to quick and tries to access it before 1password copies the OTP.
And the slide-over of another app seems to call this function again.
I would suggest a more passive approach by just allowing the user to paste in the OTP code.

**Comment by ntnhon** [comment]
Hi @wAuner, thank you for the information. We are talking about ipadOS which has more multitask scenarios than iOS, as far as I see the clipboard check function is called only in 3 cases:
1. A slide-over app is closed (swiped up).
2. A slide-over app is chosen to be on top.
3. A slide-over app becomes split screen.

I don't use 1password so I don't know how it works. My guess is that you open SimpleLogin as the main app and then you open 1password as a slide-over app to copy the OTP code. So in which case you encounter the bug?

Can you elaborate on how you use 1password alongside with SimpleLogin? And what make you see it only works 1 out 5 times?

What would you suggest precisely? A paste button does not seem a great choice for me. Where should it be?

So I'm thinking about a temporary variable which holds the last tried OTP code from the clipboard. What would you say?

**Comment by wAuner** [comment]
I've just tested it again and this time I was able to reproduce the surprising behavior:
On the login screen I select the password helper on the ios keyboard and it opens 1password. 1password fills out email and password and automatically copies the OTP code in the clipboard, so that I can paste it in a specific webform (like on amazon etc). Usually that works by touch and hold and then select paste. But this doesn't work with the current GUI for entering the code.

When I pull in my slide-over apps from the right (no matter which app) the function accesses my clipboard. If I do it immeaditely it works. If I wait a bit, it copies the old code and gives an error.
This is very confusing to the user because the user didn't enter anything. This was also the reason why I initially thought that 2FA wasn't used at all.

I would suggest the following: Don't access the user's clipboard actively. This can be super confusing to the user.
If you don't want to add a paste button (which I think wouldn't be such a bad idea), just allow the normal iOS/ipadOS behavior (press and hold, then select paste).

**Comment by ntnhon** [comment]
I came to this [solution](https://github.com/simple-login/Simple-Login-iOS/commit/1f42775b9ebde116a9ce9a42576146024afe6d72) using a snackbar. What do you think @wAuner ?

iPad:
![iPad](https://user-images.githubusercontent.com/4153453/80977890-a5834880-8e25-11ea-87b0-b32a9c16204e.png)

iPhone:
![iPhone](https://user-images.githubusercontent.com/4153453/80978145-f430e280-8e25-11ea-9641-dbb1c2dd2e54.PNG)

**Comment by wAuner** [comment]
looks great!

**Comment by ntnhon** [comment]
@wAuner: the update is approved by Apple. Have a look.

**Comment by wAuner** [comment]
ok I've tested it again. The snake bar looks good and works well, but the triggers (the events that call the function) aren't quite there yet. The problem remains the still the same.
![IMG_0214](https://user-images.githubusercontent.com/18383180/81043785-85459f00-8ea2-11ea-8d4c-6c4164d822f6.jpeg)
The OTP Token is copied to the clipboard when I let the password manager fill in the login data.
The current behavior parses the clipboard when I use a multitasking app via swipe over (either when this app requires face id or I switch to another app). This is not helpful.

I would suggest to parse the clipboard only once when the "Enter OTP" screen shows up. And in addition make the OTP text field "pastable" such that the user can paste a copied OTP code in that field or use drag and drop to place it there.

**Comment by ntnhon** [comment]
I see clearly the problem now, it is because 1password automatically copies the OTP code in the background and let user know through a notification. This is not what I expected in the current scenario which relies on application level lifecycle change (app becomes active again), which happens on app switch, not on receiving a notification which doesn't fire a lifecycle change.

I will think about how to make the code "pastable" as you suggest. I was wondering because each digit is a label, they are not textfields which can receive input (paste). Maybe I will go for a long press gesture for each label to display a paste tooltip.

**Comment by ntnhon** [comment]
@wAuner: user can now long press to paste the code (see this [commit](https://github.com/simple-login/Simple-Login-iOS/commit/6d553a38628c57b3643db08df3b1a00b8985220b)). Note that the paste tooltip is only displayed when the copied text in the clipboard is in correct format (6 digits string) otherwise nothing happens.

![IMG_4969](https://user-images.githubusercontent.com/4153453/81112004-3fc6b780-8f1e-11ea-89cd-4aa6bedf327d.PNG)

**Comment by ntnhon** [comment]
@wAuner: the new release with this fix is approved. Let me know what you think :)
