### ISSUE TITLE
[enhancement] Hide the note space if the alias as no any note associated

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#101]
As in the title, I think that would help to gain more space. The UX would be marginally touched, almost not touched I'd say. That note icon near the note space does not allow to directly edit the note, so the mechanism to create/edit a note would not change at all.

![image](https://user-images.githubusercontent.com/36189429/165350413-9efd8bea-e5eb-442c-b202-0e89356d1aaf.png)

**Comment by ntnhon** [comment]
Hello, I saw and fixed this while working on other issue. Thanks for reporting anyway, please keep doing 👍

**Comment by wizard86pz** [comment]
Confirmed the fix in build 20023. Thanks again.

**Comment by ntnhon** [comment]
You're most welcome!
