### ISSUE TITLE
No way to sync the "my account" section info

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#105]
No way to sync the "my account" section info without remove the app from the recent ones, killing it, and re-opening it.

Scrolling the section do not trigger a forced sync.

It could be taken in consideration in case of any change on web, to see updated info on iOS app too.

Build 20024.

**Comment by ntnhon** [comment]
Hello, this is done. I'll make a new build later.

**Comment by ntnhon** [comment]
Thank you! I'll try to fix it later.

**Comment by wizard86pz** [comment]
> Thank you! I'll try to fix it later.

Thanks. Are you able to reproduce it?

**Comment by ntnhon** [comment]
Yes, on a device with iOS 15. The one I use for development is in iOS 14 that's why I don't see the bug in the first place.

**Comment by wizard86pz** [comment]
> Yes, on a device with iOS 15. The one I use for development is in iOS 14 that's why I don't see the bug in the first place.

Got it. Not problem. I'm happy to cover iOS 15 users.

**Comment by ntnhon** [comment]
I'm graceful that you literally do the job of a QA. People don't always upgrade iOS even though they can. So I leave my development phone in iOS 14 on purpose because it's easy to upgrade but almost impossible to downgrade 😄

**Comment by wizard86pz** [comment]
Yeah, this has sense.

**Comment by ntnhon** [comment]
Well, I didn't really fix it, it's fixed by itself 😅

**Comment by wizard86pz** [comment]
So strange, I really can't reproduce it longer.
