### ISSUE TITLE
Add back button here

### ISSUE THREAD

**Issue by sleeping10** [simple-login/Simple-Login-iOS#116]
Hi, when you want to send an email via an alias and press the button “send mail” works fine from “all,” active,” and inactive. They all have back button. But when you search for for aliases and press send the back button is not there looks like you are stuck. You can go back by sliding down, but it took time to understand that.

Back button 
![image](https://user-images.githubusercontent.com/37278143/166146192-1a17827a-e95b-4ec5-ac2c-dea572a76145.png)

No back button 
![image](https://user-images.githubusercontent.com/37278143/166146287-d79d83e1-9270-40eb-987c-8ebeeb3c46dd.png)

**Comment by wizard86pz** [comment]
Nice catch! I can reproduce it.

iOS 15.4.1.
Client build 20026.

**Comment by ntnhon** [comment]
Hello, thanks a lot for reporting. I'll fix this soon.

**Comment by wizard86pz** [comment]
Still reproducible in latest TF beta build 2.0.0 (20029).

**Comment by wizard86pz** [comment]
Fixed confirmed in build 20030. Thanks.
