### ISSUE TITLE
Use website name when creating a new alias via the keyboard

### ISSUE THREAD

**Issue by nguyenkims** [simple-login/Simple-Login-iOS#117]
Currently a totally random alias is created. For example in the below screenshot, the alias is created on reddit but doesn't contain the reddit prefix.

It'd be nice the website can be used to create the alias:

![image](https://user-images.githubusercontent.com/3167780/166460955-f34125ef-de15-42e7-9d33-65ff4d9c169b.png)

**Comment by ntnhon** [comment]
This is impossible because the keyboard doesn't have knowledge about such information. Share Extension is more appropriate in this case.

**Comment by nguyenkims** [comment]
I see, we can maybe consider adding a full keyboard in SL in the future then. https://getkeyboardkit.com/ seems promising.

**Comment by ntnhon** [comment]
Yes I know this library and the author. We can consider using it to make a full-fledged keyboard later.
