### ISSUE TITLE
[Share Extension] Able to share a text

### ISSUE THREAD

**Issue by ntnhon** [simple-login/Simple-Login-iOS#118]
For now the Share Extension can only be open if the users share an URL. Make it able to also handle a text, try to detect the URLs available in the text, pick the first URL if there are many and continue the flow as normal. If the text contains no URLs, make the text the default notes of the alias.

**Comment by bradenglund** [comment]
I see you closed #117 already. I think we're all going the same direction here in what we want/need in terms of functionality. If the keyboard cannot access the URL, I see how that that could be challenging to implement.

It feels like we are trying to come up with a workaround for system limitations.

**Comment by ntnhon** [comment]
Yes it's kind of a workaround as you said. I think it's a tiny easter egg which is not really necessary but nice to have.
