### ISSUE TITLE
Opening the app, the list of aliases is not updated

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#125]
As in the title. I think that when the user opens the app, it's supposed to see an updated status of his aliases list, so the app should probably make a sync at the launching. The user needs to manually swipe down the list from the top, to see updated list of aliases created by SL keyboard, or by other client, or via web app.

TF build 20028.

**Comment by ntnhon** [comment]
Opening an app can have 2 scenarios:
1. App is killed: app is launched and it will load the latest list of aliases
2. App is in background: app goes back to foreground and it does nothing.

I think you're talking about the 2nd scenario. Can you confirm please?

**Comment by ntnhon** [comment]
Okay, I see. Real time sensitive apps like facebook, such behaviour is expected but in the case of a simple app like SL it's not really necessary in my opinion. Take the SL web app for example, an equivalent of what you are talking about is to have the web app refreshes itself every time you go back to SL tab from another tab.
