### ISSUE TITLE
Add contact function (reverse alias creation and sender block)

### ISSUE THREAD

**Issue by GregBnt** [simple-login/Simple-Login-iOS#126]
Hello, to make the application even more practical, it would be necessary to add the "contact" button for each alias (as on the web version). In order to be able to create a reverse alias by entering a contact (point 1), or to be able to block senders in each alias (point 2).

![CleanShot 2022-06-05 at 19 07 23@2x](https://user-images.githubusercontent.com/106819553/172061997-ce0f6194-f806-4872-a41d-cc1b0b7ab5fb.png)

Thank you in advance!

**Comment by ntnhon** [comment]
Hello, indeed there's "Send email" button which offers what you say. I renamed it from "Send email" to "Contacts" to make it the same as the web version and less confusing.

**Comment by GregBnt** [comment]
> Hello, indeed there's "Send email" button which offers what you say. I renamed it from "Send email" to "Contacts" to make it the same as the web version and less confusing.

Hi, thank you for this addition, but it lacks the ability to block or unblock contacts. Currently you can only copy reverse alias but not block or unblock a mail.

**Comment by ntnhon** [comment]
Yes you can by just tapping on the contact. A menu will pop out and there's a block option.
![Screenshot 2022-07-28 at 13 45 08](https://user-images.githubusercontent.com/4153453/181497321-a455d3bd-65be-4306-a2aa-fbcde43f8684.png)

**Comment by GregBnt** [comment]
I am on version 20030 and I do not have this addition. :/
![photo_5987672577063106855_y](https://user-images.githubusercontent.com/106819553/181498967-7345f728-bb2a-4de3-a260-92cbc7a7680b.png)

**Comment by ntnhon** [comment]
Ah you're right we were talking about different pages. I was talking about "Contacts" page. The page you are showing is "Alias detail" page. Currently both mobile apps and web app don't support block/unblock from this page.

**Comment by GregBnt** [comment]
What do you mean by the "contact" page? Is this on the TestFlight beta? Cau on my app, I only have "Aliases, Advanded, Settings and My Account".

**Comment by ntnhon** [comment]
"Contacts" page is accessible either by tapping this "Send email" button
![IMG_1C26D3DED06C-1](https://user-images.githubusercontent.com/4153453/181504356-1fa122cc-bbcc-4987-a21b-d95a7c8fceda.jpeg)
Or this 

![IMG_079A9D993D32-1](https://user-images.githubusercontent.com/4153453/181504526-7d698816-4f8b-4ecf-9c26-de0c55598422.jpeg)

Which I recently change to "Contacts" instead of "Send email" to avoid confusion. But this is not yet in TestFlight.

**Comment by GregBnt** [comment]
Oh great, I found it, thank you so much. Indeed, with the name change, it will be clearer. :)

**Comment by ntnhon** [comment]
You're welcome :)
