### ISSUE TITLE
"mailboxes" menu does not work from the alias search result list

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#131]
1. Search for an alias;
2. press on the search result;
3. tap on "MAILBOXES" menu.

Result: nothing happens.

Desired: to have a working menu.

Involved build: TF v2.0.0 (20030).

NOTE: not always reproducible. The "mailboxes" menu is generated, but on an hidden layer, somehow. Indeed if you come back to the search result, press on the same search result and then on the "mailboxes" menu, it appears correctly.

**Comment by ntnhon** [comment]
Fixed in #136

**Comment by wizard86pz** [comment]
Fixed in TF beta v2.0.0 (20031). Thanks.
