### ISSUE TITLE
"DISPLAY NAME" input filed does not work from the alias search result list

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#132]
1. Search for an alias
2. press on the search result
3. tap on "DISPLAY NAME" input field

Result: nothing happens

Desired: to have a working input field.

Involved build: TF v2.0.0 (20030).

NOTE: not always reproducible. The "DISPLAY NAMES" menu is generated, but on an hidden layer, somehow. Indeed if you come back to the search result, press on the same search result and then on the "DISPLAY NAME" input field, it appears correctly.

**Comment by ntnhon** [comment]
Fixed in #136

**Comment by wizard86pz** [comment]
Fixed in TF beta v2.0.0 (20031). Thanks.
