### ISSUE TITLE
Add templates in the alias display mode settings

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#138]
Hello,
I'd suggest to add templates/graphical examples of the 3 modes, while the user is selecting the desired alias display mode.

This would help to immediately get the differences in terms of details/info that the user will/will not see in the alias list.

I mean here:
![image](https://user-images.githubusercontent.com/36189429/181788165-497d9dd7-4f53-42d1-94b3-10813d95cb07.png)
![image](https://user-images.githubusercontent.com/36189429/181788179-46d344d0-13f7-47d7-bffa-c5ede498bb08.png)
![image](https://user-images.githubusercontent.com/36189429/181788195-382a2d36-75f5-43b8-bb60-c5f75ac8589e.png)

**Comment by wizard86pz** [comment]
@nguyenkims what do you think?

**Comment by ntnhon** [comment]
I think @wizard86pz is talking about making the preview more clear by providing sample data for each display mode instead of just grey boxes.

**Comment by ntnhon** [comment]
Like "Context menu" example on tips page
![IMG_204804879ADB-1](https://user-images.githubusercontent.com/4153453/182167745-66a70663-9fa3-4d77-89c3-2c11e5b0d58c.jpeg)

**Comment by wizard86pz** [comment]
> I think @wizard86pz is talking about making the preview more clear by providing sample data for each display mode instead of just grey boxes.

Yes @ntnhon, that's what I meant. Thanks.

**Comment by nguyenkims** [comment]
@wizard86pz @ntnhon Oh I see, in this case this totally makes sense 👍
