### ISSUE TITLE
The data couldn't be read because it is missing

### ISSUE THREAD

**Issue by darkfence** [simple-login/Simple-Login-iOS#142]
After updating to the new version of the SL iOS app I am unable to use it with my self-hosted SL. Logging in works, my aliases are showing but I’m unable to create a new one or edit existing alias. Every action ends with empty screen with mentioned error “The data couldn’t be read because it is missing”. 

I am using 2.0.1 version of iOS client and simplelogin/app:3.4.0 on my server.

**Comment by nguyenkims** [comment]
@darkfence the new ios version uses some endpoints that are only available in the next self-hosted version, I'd recommend to upgrade to this version on  https://github.com/simple-login/app/tree/4.6.2-beta

It's currently beta and will be made public soon.

**Comment by ntnhon** [comment]
Please update your self-hosted SL and feel free to reopen if the issue persists.
