### ISSUE TITLE
The data could not be read because is missing

### ISSUE THREAD

**Issue by Heziode** [simple-login/Simple-Login-iOS#143]
When I attempt to acces to the "My Account" tab, I got the following message: `the data could not be read because is missing`

# Context

**App version**: latest (2.1.0)
**iOS version**: 15.6
**instance**: custom instance
**login method**: email + password, since I got the same error as describe here, when I attempt to use the API Auth.

Remark: API Auth work with browser extension

**Comment by nguyenkims** [comment]
Can you upgrade the self host instance to the latest version which is https://github.com/simple-login/app/tree/4.6.2-beta ?

**Comment by Heziode** [comment]
Ok, I check that this week.

Is there a way to check the current version of the running Simple Login instance? The version is not show on the dashboard, and I cannot find a way to see it with the docker container (I build a version from a specific commit, not from the docker hub)

**Comment by nguyenkims** [comment]
You can go to `{URL}/git` which should return the Git SHA1 that the code is running on.

**Comment by Heziode** [comment]
Hi @nguyenkims I am trying to update from [simple-login/app/67dad33b700d86c9364092f8efa32fe289fcc5e0](https://github.com/simple-login/app/commit/67dad33b700d86c9364092f8efa32fe289fcc5e0) to [4.6.2-beta](https://github.com/simple-login/app/tree/4.6.2-beta) but it seems it does not work properly, when I follow the instruction in upgrade:

```bash
docker run --rm \
    --name sl-migration \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/sl/upload:/code/static/upload \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    -v $(pwd)/simplelogin.env:/code/.env \
    --network="sl-network" \
    local/simple-login-app:4.6.2-beta flask db upgrade

docker run --rm \
    --name sl-init \
    -v $(pwd)/sl:/sl \
    -v $(pwd)/simplelogin.env:/code/.env \
    -v $(pwd)/dkim.key:/dkim.key \
    -v $(pwd)/dkim.pub.key:/dkim.pub.key \
    --network="sl-network" \
    local/simple-login-app:4.6.2-beta python init_app.py
```

Where `local/simple-login-app:4.6.2-beta` is my clone of `app` on `4.6.2-beta` branch. I have rebulid the image of course.

**Comment by Heziode** [comment]
Ok, I have updated to the `simplelogin/app:4.6.2-beta` version, and the problem is still here

**Comment by nguyenkims** [comment]
Can you try to upgrade to our currently running version which is `simplelogin/app-ci:v4.14.0` and check if the issue is still there?

**Comment by Heziode** [comment]
I updated to `simplelogin/app-ci:v4.14.0 `, now I got a new error: "Unknown error with status 500" 😂:


```
2022-08-30 21:17:38,080 - SL - ERROR - 8 - "/code/server.py:380" - error_handler() -  - ProtonPartnerNotSetUp 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/app/api/base.py", line 52, in decorated
    return f(*args, **kwargs)
  File "/code/app/api/views/user_info.py", line 59, in user_info
    return jsonify(user_to_dict(user))
  File "/code/app/api/views/user_info.py", line 32, in user_to_dict
    "connected_proton_address": get_connected_proton_address(user),
  File "/code/app/api/views/user_info.py", line 18, in get_connected_proton_address
    proton_partner = get_proton_partner()
  File "/code/app/proton/utils.py", line 17, in get_proton_partner
    raise ProtonPartnerNotSetUp
app.errors.ProtonPartnerNotSetUp: ProtonPartnerNotSetUp 
2022-08-30 21:17:38,083 - SL - DEBUG - 8 - "/code/server.py:276" - after_request() -  - 82.65.113.228 GET /api/user_info ImmutableMultiDict([]) 500, takes 0.039659738540649414
2022-08-30 21:17:38,085 - SL - DEBUG - 7 - "/code/server.py:276" - after_request() -  - 82.65.113.228 GET /api/v2/setting/domains ImmutableMultiDict([]) 200, takes 0.04241490364074707
2022-08-30 21:17:38,121 - SL - DEBUG - 8 - "/code/server.py:276" - after_request() -  - 82.65.113.228 GET /api/setting ImmutableMultiDict([]) 200, takes 0.028625011444091797
```

**Comment by nguyenkims** [comment]
This error has been fixed in `simplelogin/app-ci:v4.14.3`, can you please try this version instead?

**Comment by Heziode** [comment]
This, and a succession of other problems, led me to abandon self-hosting. I migrated my domain name directly to the version managed by you.

With the managed version, there is no problem with the app :)

**Comment by nguyenkims** [comment]
@Heziode as the iOS version release cycle is independent to the self-hosting release calendar, discrepancies can unfortunately happen ... We'll try to release the server code more often so the 2 versions stay compatible.

**Comment by Heziode** [comment]
I know that the validation process on iOS can be a bit boring, so, courage 💪

(I always managed to dev PWA to avoid developing an app for Android and iOS 😂)

**Comment by nguyenkims** [comment]
@Heziode thanks :). We use some features like keyboard extension, share menu, etc. that require a native apps so PWA isn't an option for us.

**Comment by Heziode** [comment]
I have just tested with the latest version `v4.14.4` on the custom instance, and it works now.

I close this issue since the problem is solved.
