### ISSUE TITLE
Impossible to force the alias list updating/sync scrolling down

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#148]
As in the title.

STR:
1. open the app and go to the "Aliases" section
2. scroll down the list from the top

There is no forced sync.

Workaround: switch to the active or inactive tab, go back to the All on and you'll able to trigger the manual sync, scrolling down the list.

Note: appeared only after iOS update to v16.

iOS 16.0 (20A362)
Client: 2.2.0 (build 22000).

**Comment by ntnhon** [comment]
Hi, thanks for reporting. I'll investigate and try to fix this.

**Comment by wizard86pz** [comment]
Updated STR:

1. open the app
2. Go back too home screen
3. go to the "Aliases" section if you've left the app from a different section
4.scroll down the list from the top

**Comment by ntnhon** [comment]
Hello, sorry for the delay. It should be fix with the new version 2.3.0.

**Comment by wizard86pz** [comment]
> Hello, sorry for the delay. It should be fixed with the new version 2.3.0.

It is, thanks!
