### ISSUE TITLE
Wordings change

### ISSUE THREAD

**Issue by ghost** [simple-login/Simple-Login-iOS#151]
Reply -> Reply/Sent (Because you can also SEND from alias, not only reply)

![9EAAAF84-3615-4709-921A-2852A7E9235E](https://user-images.githubusercontent.com/120200229/206858071-8e104125-27e5-4c87-b7f9-f85f8bb0bbe7.jpeg)

Account -> app (Because won’t protect an _account_, it will protect the app with logged in account)

![A418DA92-CA04-47A0-B700-DD9E782F4673](https://user-images.githubusercontent.com/120200229/206858137-82ced6ce-83bc-4742-ae96-fb46fa68b302.jpeg)

TOO big text. It is inconvenient.

![75A7FEB2-DFBE-43C9-BFD0-3B09E31878CF](https://user-images.githubusercontent.com/120200229/206858192-eac0715b-0b4d-4dad-a54a-85c7da867bb0.jpeg)

Remove information about adding email. It can be a risk for privacy.

![28ED562D-D046-4A94-B3A4-663047FE5495](https://user-images.githubusercontent.com/120200229/206858320-82e7bf7b-dd3c-4744-9f80-e5c7ae45921a.jpeg)

Search term -> search (it will be more accurate)

![F7CB721B-5FD0-4514-9712-5CF90459E877](https://user-images.githubusercontent.com/120200229/206858384-7f88b807-a85a-457c-a9af-97f2ddb4ce21.jpeg)

**Comment by ntnhon** [comment]
They are fixes in this commit: https://github.com/simple-login/Simple-Login-iOS/pull/159/commits/55f3eb435da6445b37815fb13f3e4b2602918a33
