### ISSUE TITLE
Add: `ignoresSafeArea()`

### ISSUE THREAD

**Issue by mainbennyx** [simple-login/Simple-Login-iOS#158]
Add: `ignoresSafeArea()` to 
https://github.com/simple-login/Simple-Login-iOS/blob/2167242ccf58221c8fbec67141f74bc0131194c0/SimpleLogin/SimpleLogin/SimpleLoginApp.swift#L61

/* I'm currently a newbie in swift and with GitHub but as far as I understand it, it should remove the gray area at the bottom while unlock with Face ID 
![IMG_0239](https://github.com/simple-login/Simple-Login-iOS/assets/93770422/4b410360-0f1d-4245-9589-d9b944993684)
*/

**Comment by ntnhon** [comment]
Thanks for your suggestion, it's implemented here: https://github.com/simple-login/Simple-Login-iOS/pull/159/commits/c1f323b2e2a8639d1a62ace67c31731e7c9d83cc
This will be included in our next release 👍
