### ISSUE TITLE
Name & Note display in different order in browser extension vs iOS app

### ISSUE THREAD

**Issue by OddHouseGames** [simple-login/Simple-Login-iOS#18]
The following information is displayed in a different order in both instances.

iOS Mobile App
1. Mailbox
2. Name
3. Note

Web Browser Extension
1. Mailbox
2. Note
3. Name

The order of Name/Note changes, it would be great to have a common experience in both interactions.

**Comment by ntnhon** [comment]
Thank you for the feed back. We'll have it fixed soon :)
