### ISSUE TITLE
Unable to create random alias

### ISSUE THREAD

**Issue by Sc0tTyXL** [simple-login/Simple-Login-iOS#28]
Hi,

The App only has an option to create a named alias.
There is no option for a random alias (UUID or words) can this be added as it's my number 1 use-case for the app.
I've been using the mobile site to this.

Thank you

**Comment by ntnhon** [comment]
Hello, you can shake the phone on homepage and the app will let you random an alias by word or UUID. I know this is not so obvious and I'm working on renewing the whole UI.

**Comment by Sc0tTyXL** [comment]
O wow haha, yeah that works!

Would be great to get a physical button as I personally don't like the shake gesture.
And from a UX perspective the discoverability is low.

**Comment by ntnhon** [comment]
Absolutely! FYI I'm working on rewriting the whole app in SwiftUI. It'll take some time but I hope the result will be worth it :)

**Comment by jasperweiss** [comment]
I wish I knew this sooner 🙄
I like the uniformity of having totally random UUID address for all acounts in my password manager but I couldn't find a way to make those within the iOS app so some of them are random UUID's and some of them are named. Oh well, #firstworldproblems I guess 😅.
