### ISSUE TITLE
Cannot login - status code 403

### ISSUE THREAD

**Issue by alanhblin** [simple-login/Simple-Login-iOS#3]
I cannot login the ios app with my email address and password.  A message popped up "unknown error with status code 403".

SimpleLogin ios app v.1.4
iOS version 13.7
iphone X

**Comment by ntnhon** [comment]
Hi @alanhblin, are you self-hosting SimpleLogin?

**Comment by alanhblin** [comment]
No. I use simplelogin.io.

I set up Security Key (WebAuthn), but not TOTP.  Would that be the source of problem (perhaps because WebAuthn is not supported in iOS app)?

**Comment by ntnhon** [comment]
I got it, the mobile versions haven't supported yet other login method than regular email/password and api key. Please use api key as an alternative for the moment. I will leave the issue opened and have you updated :)

**Comment by alanhblin** [comment]
API key works for me. Thank you.
