### ISSUE TITLE
Auto-generate aliasPrefix like browser extension

### ISSUE THREAD

**Issue by bradenglund** [simple-login/Simple-Login-iOS#33]
The safari/iOS extension from the share sheet currently has a popup where you can type a prefix to create the new alias. The iOS version should function the same as the browser extension where it will automatically generate the `aliasPrefix` from the hostname and `signedSuffix` and pre-fill the form for you.

![2021-11-30 13_17_55-](https://user-images.githubusercontent.com/28195153/144104833-3d44678c-3d99-452b-8842-14da99a812d3.png)

Adding the `createRandomAlias` function would be great too, but maybe better a separate issue.

**Comment by nguyenkims** [comment]
@bradenglund currently the Safari extension uses a different codebase and we plan to use the same Chrome/Firefox extension for Safari now that Safari (finally) supports the web extension API. In the next version, it's going to behave the same as Chrome/Firefox extension :)

**Comment by ntnhon** [comment]
The share extension can now extract the hostname from the URL. It will also try to ignore "www" to pre-fill a meaningful hostname. A new release will be available very soon.
