### ISSUE TITLE
Unable to Login on the iOS App

### ISSUE THREAD

**Issue by broganbrogan** [simple-login/Simple-Login-iOS#4]
I am on version 1.4 I get the following error message "Unknown error with status code 403"
![unnamed](https://user-images.githubusercontent.com/58822928/104304023-b0e04680-547f-11eb-9b30-692de2f522bb.jpg)

**Comment by broganbrogan** [comment]
As of 1/12/2021 you have to sign in with your API key.

**Comment by ntnhon** [comment]
Hello, this is because the app haven't yet supported WebAuth. As you said for now you can log in using API key. Sorry for the inconvenience, we are working on it.
