### ISSUE TITLE
Support random alias functionality

### ISSUE THREAD

**Issue by dannydarvish** [simple-login/Simple-Login-iOS#43]
It would be great to support all the random alias functionality that the website has. This is my most common way of creating aliases, so the app is currently not very helpful for my use case.

**Comment by ntnhon** [comment]
Hello, the current app does support random alias by shaking the device. It's not something intuitive so we're are working a new version with a completely new UI. It's open for beta testing via TestFlight: https://testflight.apple.com/join/atEnn7SL

Look forward to your feedback.
