### ISSUE TITLE
App sign-in URI is blank

### ISSUE THREAD

**Issue by bradenglund** [simple-login/Simple-Login-iOS#46]
Testing new testflight version 2.0.0 (20008) and I was forced to sign in again. When using the native iOS username/password auto-fill, no URI parameter is set for the login.

Setting https://simplelogin.io/ as the login URI will enable auto-fill matching for the app.

iOS v15.3.1

**Comment by ntnhon** [comment]
Hello, thank you for the feedback. Are you forced to sign in again multiple times? If it's just the first time it's something expected as there is a change related to Keychain identifier.

Can you elaborate on how to set the login URI?

**Comment by bradenglund** [comment]
I think this should help. I think the issue is setting Associated Domains for the app.
https://developer.apple.com/documentation/security/password_autofill/about_the_password_autofill_workflow

**Comment by ntnhon** [comment]
Hello, please test the 20012 build and let me know if it autofills correctly.

**Comment by bradenglund** [comment]
It works!
