### ISSUE TITLE
Text wrap issue on My account page

### ISSUE THREAD

**Issue by bradenglund** [simple-login/Simple-Login-iOS#47]
The descriptors for "ultra-protection" and "Force dark mode" do not wrap properly and are cut off from view. See screenshot.

![Attachment0](https://user-images.githubusercontent.com/28195153/158378488-95e56946-11c5-4d29-b1a7-9b9b80247249.jpeg)

**Comment by ntnhon** [comment]
Hello, I remembered fixing this bug already but maybe it's a regression after I tried to refactoring something.

**Comment by ntnhon** [comment]
Please update to the new build (20009) and let me know if the issue persists.

**Comment by bradenglund** [comment]
Fixed
