### ISSUE TITLE
TestFlight API login not working

### ISSUE THREAD

**Issue by Ghost-Recon131** [simple-login/Simple-Login-iOS#48]
I can't login using an API key on the Testflight Build. I get a "Invalid API URL" error. API URL on default and unchanged. 

Tested on
iPhone 13 Pro
Home internet connection & Cellular

![IMG_4030](https://user-images.githubusercontent.com/40227626/158726001-a310aafd-aec1-4a7e-8277-0c6d3a103a91.PNG)
![IMG_4031](https://user-images.githubusercontent.com/40227626/158726003-8a425fe5-7b24-4588-a0c3-dd83b9306eba.PNG)

**Comment by ntnhon** [comment]
Hello, can you please try to force an update by resetting or editing the API URL?

**Comment by Ghost-Recon131** [comment]
> Hello, can you please try to force an update by resetting or editing the API URL?

Just tried and still getting the same error

**Comment by ntnhon** [comment]
That doesn't make much sense to me for now. What if you log in using email & password? You also have the same error?

**Comment by Ghost-Recon131** [comment]
> That doesn't make much sense to me for now. What if you log in using email & password? You also have the same error?

Email & password works fine

**Comment by Richie2022BM** [comment]
I had the same problem. The way i did it was login in my laptop and deleting 2FA and created another one, but this need to be solved. Take care guys.

**Comment by ntnhon** [comment]
Please update to the new build (20009) and let me know if the issue persists.
