### ISSUE TITLE
Non active alias bug

### ISSUE THREAD

**Issue by sleeping10** [simple-login/Simple-Login-iOS#49]
Hi thanks for the new look in the beta looks excellent. When you open the app and press inactive alias there is nothing until you scroll through all the alias in "all" then you can see the inactive alias. Small UI thing is inactive doesn't fit the screen as seen in the screenshot.

iOS 15.4
iPhone se (2020)
App build (20008)

![image](https://user-images.githubusercontent.com/37278143/158758392-c386dc8e-b869-48f8-96c8-f7d434333e71.jpeg)

![image](https://user-images.githubusercontent.com/37278143/158758409-6c7247be-9d03-464a-93b4-0010ac45318b.jpeg)

**Comment by ntnhon** [comment]
Hello, thank you for pointing out. This is indeed a bug in the pagination process. I'll have it fixed.

**Comment by sleeping10** [comment]
It seems like you fixed the problem nice. Animation goes up over everything but still works 👍👍

iOS 15.4
iPhone se (2020)
App build (20011)

**Comment by wizard86pz** [comment]
Is this still open @ntnhon? Maybe it needs to be closed? Just guessing.

**Comment by ntnhon** [comment]
> Is this still open @ntnhon? Maybe it needs to be closed? Just guessing.

It still bugs whenever the first 20 aliases contain no inactive aliases. I'll try to fix it.
