### ISSUE TITLE
Change receiving mailbox bug

### ISSUE THREAD

**Issue by sleeping10** [simple-login/Simple-Login-iOS#50]
Hi when you have made alias and want to change the mailbox receiving. Everything works but when you press done (seen in pic 2) the app makes the changes but you have to press cancel to exit that window.

iOS 15.4
iPhone se (2020)
App build (20008)

Pic 1
![image](https://user-images.githubusercontent.com/37278143/158762562-8cdf7ec2-b2b5-417f-9ed4-322183ec5301.jpeg)

Pic 2
![image](https://user-images.githubusercontent.com/37278143/158762666-0a8a7cb4-07e5-48c0-8fb6-0c0811dea9df.jpeg)

Pic 3
![image](https://user-images.githubusercontent.com/37278143/158762718-03bda7b2-1ce4-40de-bbca-a4cb796a0db0.jpeg)

**Comment by ntnhon** [comment]
Hello, thank you for the feedback. I'll fix this.

**Comment by ntnhon** [comment]
Please update to the new build (20009) and let me know if the issue persists.

**Comment by sleeping10** [comment]
Solved 👍👍
