### ISSUE TITLE
Offline mode bug ?

### ISSUE THREAD

**Issue by sleeping10** [simple-login/Simple-Login-iOS#51]
Hi when looked at the notes for the beta it stated offline mode support when I test it out doesn't work as seen in pic 1 & 2 after I have killed the app and turn off network.
I also tried to have data load with internet on and then turn of to make offline changes that doesn't work either as seen in pic 3 screen just loading.

iOS 15.4
iPhone se (2020)
App build (20008)

Pic 1
![image](https://user-images.githubusercontent.com/37278143/158786375-4e3307b6-9158-47d4-8e3e-c29d83cebeb4.png)

Pic 2
![image](https://user-images.githubusercontent.com/37278143/158786444-20b73531-ce8a-44e7-a5bd-b6fc0b7c5ce7.png)

Pic 3
![image](https://user-images.githubusercontent.com/37278143/158786997-287ddb38-5edb-46cd-a164-26a17ebbd917.jpeg)

**Comment by ntnhon** [comment]
Hello, thank you for reporting the issue. I'll investigate more.

**Comment by ntnhon** [comment]
Hello, please update to the latest build (20026) and let me know if the issue persists.

**Comment by sleeping10** [comment]
It's still the same

**Comment by ntnhon** [comment]
Can you please check again with the latest build (20031)
