### ISSUE TITLE
Email in the same line.

### ISSUE THREAD

**Issue by Richie2022BM** [simple-login/Simple-Login-iOS#52]
Hello, good morning. I wanna congrats for the nice interface and new look. In the default display mode I recommend to show email all in the same line. Perhaps lowering the date position in order to show email all completed in the same line. I like the most default mode, because you have all the information in first sight. Take care guys.

**Comment by ntnhon** [comment]
Hello Richie, thank you for your support. I fully agree that putting the email and the date in the same line makes less room for the email. I'll make the date smaller and put it in a separated line below.

**Comment by Richie2022BM** [comment]
Hi, I want to thank you for listening my request. The look and feeling it's just perfect to me. If I see some other issue I will let you know. Thanks once again. Take care.
