### ISSUE TITLE
Time showed.

### ISSUE THREAD

**Issue by Richie2022BM** [simple-login/Simple-Login-iOS#57]
Hello once again. 
The date and time that is showing on default display mode is the date we created an email. 
If is possible to show last reply, although we have that information when we click and able to read it. Perhaps switching that information could be more useful. 

Warm regards.

**Comment by ntnhon** [comment]
Hello Richie,
Maybe we should show both creation and latest activity date? What do you think @nguyenkims?

**Comment by Richie2022BM** [comment]
Oh that would be great, if you have enough room that would be awesome. 
Thank you.

**Comment by Richie2022BM** [comment]
Just perfect. Thanks for listening. Take care.
