### ISSUE TITLE
Block sender in iOS?

### ISSUE THREAD

**Issue by sleeping10** [simple-login/Simple-Login-iOS#58]
Hi, Will block sender feature come to the app that is already on the website?

![image](https://user-images.githubusercontent.com/37278143/159183567-26b696d7-8066-43ec-a9ba-0ee388db0b00.jpeg)

**Comment by ntnhon** [comment]
Hello, yes that's right. You can now block/unblock a contact directly on the iOS app.

**Comment by sleeping10** [comment]
How can you do that can't to seem to find it ?
