### ISSUE TITLE
Customize tab bar

### ISSUE THREAD

**Issue by ntnhon** [simple-login/Simple-Login-iOS#69]
Make create alias an option at the center of the tab bar. Alias create page will be shown as a modal instead of a normal tab.

The tab bar contains 5 tab in total: Aliases - Advanced - Add - My Account - About

**Comment by nguyenkims** [comment]
@ntnhon about the last 2 items, can they be Settings and My account? We can move some settings related to user account to My account and the rest in Settings.

<img width="174" alt="image" src="https://user-images.githubusercontent.com/3167780/161385355-a6311268-f24d-4680-9911-45e45ab4e111.png">

**Comment by ntnhon** [comment]
So where should About be?

**Comment by ntnhon** [comment]
> @ntnhon About can be in the new Settings screen. So My account should contain
> 
> * the photo upload, removal
> * modify display name
> * faceID
> * Ultra protection
> * Log out
> 
> The rest and "About" can go to the new Settings page.

I find it's a bit confusing to the users. Where should "Haptic feedback" & "Force dark mode" go?
I think My Account should contain everything that is related to the functionality of the account and Settings contains all the settings that affect the functionality of the application.

My account:
- Upload/remove profile photo
- Update display name
- Newsletters
- Random mode
- Default domain
- Random alias suffix
- Sender address format

Settings:
- TouchID/FaceID
- Ultra protection
- Haptic feedback
- Force dark mode
- Alias display mode
- Keyboard extension
- About

**Comment by nguyenkims** [comment]
@ntnhon the proposition looks good to me!
