### ISSUE TITLE
Add possibility to block sender of a specific alias

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#80]
As for the web-app.

![image](https://user-images.githubusercontent.com/36189429/163408680-81185554-7cb4-4346-81a3-1d1695a0930c.png)

**Comment by ntnhon** [comment]
Hello, you can now block senders directly from the iOS app. The new version is currently in public beta, you can test it via TestFlight: https://testflight.apple.com/join/atEnn7SL

**Comment by wizard86pz** [comment]
Thanks for info. I've started to use the iOS TF beta yesterday. I've not found a way to do it.

Can you please tell me how to do it, so I can be sure there is not an issue to report about? Thanks in advance.

Using v2.0.0 (build 20016).

**Comment by ntnhon** [comment]
Yes of course! You can tap on the "Send email" button to open the contact list of an alias and then tap on a contact to reveal a list of options in which you'll find "Block" or "Unlock".

**Comment by ntnhon** [comment]
You're most welcome :)
Looking forward to your other feedback.
