### ISSUE TITLE
For an easier view and good feel.

### ISSUE THREAD

**Issue by Richie2022BM** [simple-login/Simple-Login-iOS#83]
Hello, the new feature of creating alias it's great, but now won't fit custom (where you type ) if is a bit too long. Perhaps lowering the premium or public domain word might fit everything. 

I also appreciate if can be bigger the custom words or number that you are given, perhaps in white color, just like the mailbox at the button. Thanks you and good luck guys.

**Comment by ntnhon** [comment]
Hello, this is indeed a SwiftUI problem. In iOS 14 it works fine but in iOS 15 the dropdown list is rendered differently (with the domain type instead of without). We had a discussion and we'll make the suffix picker like the one of mailboxes (push a new page instead of a dropdown list).

**Comment by ntnhon** [comment]
Hello,  new build (20018) is available.
