### ISSUE TITLE
"Copy reverse-alias" command does not copy anything

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#85]
As on the title. The issue is happening in both commands, with and without display name.

iOS app beta, v2.0.0 (20018).

![image](https://user-images.githubusercontent.com/36189429/163712310-b207a1c4-abb7-4b1c-8045-011dfa89c177.jpeg)

**Comment by ntnhon** [comment]
Hello, are you sure you have the beta build installed? Because we no longer use that prompt. You should see something similar to this
![image](https://user-images.githubusercontent.com/4153453/163730828-8ffb410d-a394-4508-a965-5b94955281e7.jpeg)

Anyway I can't reproduce the bug on both live app and beta build.

**Comment by wizard86pz** [comment]
Yes, I'm sure :) Using the following path, you'll able to reproduce the issue:

1. from the "Aliases" section of the app, press on an alias email
2. press on any email that sent an email to the alias

You'll see the "old" prompt.

Using the following path (the one you've shown in the screenshot), there will be no issues:
1. from the "Aliases" section of the app, press on "send email"
2. press on any email that sent an email to the alias

Suggestion: if the first path brings to a dead point, I'd suggest to not show any prompt once he user press on an email at the point 2 of the steps.

**Comment by wizard86pz** [comment]
Another thing that pushes me to think that prompt is un-intended is that, strangely, the 3rd command there, does its job perfectly :) It works and open the default email app on the device, pasting the reverse-alias email.

![image](https://user-images.githubusercontent.com/36189429/163731938-c480e861-0172-4450-a80e-266f93d7472e.png)

**Comment by ntnhon** [comment]
Yes you're right, thank you 👍
I'll have it fixed later this week when I come back from holidays. I'll keep you posted.

**Comment by ntnhon** [comment]
Hello, I just made a new build 20019 containing the fix.

**Comment by wizard86pz** [comment]
Yes, noticed, updated and verified: it's fixed in build 20019. Thanks.
