### ISSUE TITLE
Error Message when changing custom domain settings in v2 beta (build 20018)

### ISSUE THREAD

**Issue by jmreekes** [simple-login/Simple-Login-iOS#87]
I am getting a “The data couldn’t be read because it is missing” error message when I enable or disable the Auto create/on the fly alias setting or the random prefix generation setting for a custom domain in the app. Even though the app is generating this message, the setting change IS reflected on the web app.
![0EA56009-F392-4269-8A41-4606F806611A](https://user-images.githubusercontent.com/17210028/164710419-ea7bb639-3f81-420d-9251-3c57656d7b60.jpeg)

**Comment by ntnhon** [comment]
Hello, this error message is raised when the app doesn't receive the response in the format it expects. I'll have it fixed. Thank you for your report.

**Comment by ntnhon** [comment]
This should be fixed in build 20019
