### ISSUE TITLE
Update Alias Detail UI

### ISSUE THREAD

**Issue by ntnhon** [simple-login/Simple-Login-iOS#89]
Make more room for important details (notes, mailboxes...) & less room for less important ones (creation date, display name...)

**Comment by wizard86pz** [comment]
I like more now :)
Build 20020.

**Comment by ntnhon** [comment]
@wizard86pz Thank you! Do you find any issue so far? If not I'll just do some minor changes and merge.

**Comment by wizard86pz** [comment]
> @wizard86pz Thank you! Do you find any issue so far? If not I'll just do some minor changes and merge.

I'm doing my best to check the app in everything point. I thinking you are starting to know that I'll open issues as soon as I see something I suppose is not in tended...or that can be improved, possibly.

**Comment by ntnhon** [comment]
@wizard86pz thank you for your help 👍
