### ISSUE TITLE
The alias domain is shown on two lines (bad UI) sometimes

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#91]
Hello,
as in the title. It seems to be related to the random part between the dot (.) and the "@". If those random chars are graphically too wide, the app will show the whole alias's domain on two lines.

Affected build: 20020.

A couple of examples of the issue:

![IMG_6024](https://user-images.githubusercontent.com/36189429/164945182-08fbcb23-d247-4d5f-bef0-a72a4f471ee4.jpg)
![IMG_6023](https://user-images.githubusercontent.com/36189429/164945183-49fe2295-096d-46cb-b889-1caf8dd89ad8.jpg)

One example where the issue is not present:

![IMG_6025](https://user-images.githubusercontent.com/36189429/164945188-c5b0e1ce-ce0d-4135-802e-f46699dc2c8e.jpg)

**Comment by ntnhon** [comment]
Hello, this is expected behavior to ensure that custom prefix textfield always have enough room. I though about it and so far don't have any better idea except showing prefix and suffix in 2 separated lines which makes it feels less natural. What do you think @nguyenkims?

**Comment by nguyenkims** [comment]
@ntnhon maybe we can use less space for the custom prefix and more for the suffix? Otherwise I think that's ok to show on 2 lines as phone screen width is quite limited.

**Comment by wizard86pz** [comment]
> @ntnhon maybe we can use less space for the custom prefix and more for the suffix?

For what it matters, I like this. I'm facing this on iPhone 12. Not a very small device/screen.

**Comment by wizard86pz** [comment]
I like it, thank you.

![image](https://user-images.githubusercontent.com/36189429/164996058-3790eafe-3d6b-4a6e-b052-a4b899b2d8f4.jpeg)

**Comment by ntnhon** [comment]
@wizard86pz You're most welcome! I'm glad that you like it :)
I'll wait a bit for eventual feedbacks.
