### ISSUE TITLE
After to have created a new alias email, reopening the app, the new alias creation prompt is always shown

### ISSUE THREAD

**Issue by wizard86pz** [simple-login/Simple-Login-iOS#98]
As in the title.

This is the interested prompt:

![image](https://user-images.githubusercontent.com/36189429/165088979-7c0ab553-5765-452f-9fe5-83571e0faaf6.jpeg)

I've fixed it only killing the app from recent ones, and then re-openning it. Once I create a new alias, the issue happens again.

Build 20021.

**Comment by ntnhon** [comment]
Which iOS are you on? I can't reproduce it on iOS 14.2 and 14.7.1
Anyway I just made some changes related to this prompt, please test the build 20022 and let me know if it persists.

**Comment by wizard86pz** [comment]
I'm from iO 15.4.1 (19E258).

Just reproduced on build 20022 too.

**Comment by ntnhon** [comment]
Okay thank you, I'll try to fix it.

**Comment by wizard86pz** [comment]
Another info to confirm that there is an issue:

1. create an alias
2. switch to another app
3. switch back to the SimpleLogin app
4. delete the alias object of the new alias creation prompt

The prompt continues to be shown to every switch back to the app, or opening it via icon app.

**Comment by wizard86pz** [comment]
Got it, I'll try to find the triggering condition. I'll let you know in case I found something.

**Comment by wizard86pz** [comment]
@ntnhon I think to have found the triggering condition: in the app settings, you need to enable the "Ultra-protection" feature. I can reproduce the issue only under this condition.

**Comment by ntnhon** [comment]
@wizard86pz You're right, I can now reproduce and that makes more sense now. A huge thank to you!
